# Profile information
name: D&D Fun Factory
title: D&D Fun Factory
description: > # this means to ignore newlines until "baseurl:"
  D&D Fun Factory - The Place for all your Daddy and Daniel Fun
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dndfunfactory.com" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: #Add your Google+
github: #Add your Github

# Contact form
email: dndfunfactory@protonmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
